---
docker_users: ["docker"]
home: /home/docker
user: docker
docker_directory: docker_data
docker_install_compose: True
postgres_directory: pg_data
pip_install_packages:
  - name: docker

  
grucloud_image: "fredericheem/grucloud-cli:v1.16.0"
docker_base_url: "http:/v1.41"
# Docker image tag names
api_image: "fredericheem/api"
api_tag: v10.29.0

web_image: "fredericheem/ui"
web_tag: v10.33.0

firewall_state: started
firewall_enabled_at_boot: true
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# Database settings
db_username: "docker"
db_hostname: "pg"
db_database: "prod"
# External volume
db_data_dir: "/data/pg_data"

server_name: default
protocol: "https"
ssl_admin_email: "hello@grucloud.com"
production: "FALSE"
network: "mainnet"

mail_from: "StarHackIt <notification@starhack.it>"
mail_signature: "The StarHackIt Team"
mail_service: "Mailgun"
